apiVersion: apps/v1
kind: Deployment
metadata:
  name: threat
spec:
  selector:
    matchLabels:
      app: threat
  template:
    metadata:
      labels:
        app: threat
    spec:
      containers:
      - name: threat
        image: itsadeadh2/hxt-threat
        ports:
        - containerPort: 3000
          name: threat-port
        env:
          - name: DB_CONNECTION
            value: 'mongodb://hvt-mongodb/ThreatDB'
          - name: POWER_API
            value: 'power-service'
