http:
  port: 8080
# admin:
#   port: 9876
#   host: hvt-gateway-service
apiEndpoints:
  hero:
    host: '*'    
    paths: 
      - /hero/*
      - /hero
  power:
    host: '*'
    paths: 
      - /power/*
      - /power
  threat:
    host: '*'
    paths:
      - /threat/*
      - /threat
serviceEndpoints:
  hero:
    url: 'http://hero-service'
  power:
    url: 'http://power-service'
  threat:
    url: 'http://threat-service'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  pipeline_1:
    apiEndpoints:
      - hero      
    policies:
      - log:
          - action:
              message: ${req.method} - ${req.originalUrl}
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: hero
              changeOrigin: true
  pipeline_2:
    apiEndpoints:
      - power      
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - log:
          - action:
              message: ${req.method} - ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: power
              changeOrigin: true
  pipeline_3:
    apiEndpoints:
      - threat      
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - log:
          - action:
              message: ${req.method} - ${req.originalUrl}
      - proxy:
          - action:
              serviceEndpoint: threat
              changeOrigin: true